- ignore: {name: "Collapse lambdas"}
- ignore: {name: "Use ?~"}
- ignore: {name: "Use newtype instead of data"}
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Use when"}
- ignore: {name: "Use ||"}
